name: Alerta DevOps ITLA

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar programa Hola Mundo
        run: node hola.js

      - name: Enviar notificaciÃ³n a ntfy
        run: |
          curl -H "Title: Push detectado" \
               -H "Priority: high" \
               -d "Se subiÃ³ cÃ³digo a la rama main del repositorio ðŸš€" \
               https://ntfy.sh/devops-itla
